version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  transaction-file-bridge:
    image: your-dockerhub-username/transaction-file-bridge:latest
    container_name: transaction-file-bridge
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: transactions
      INPUT_PATH: /app/input
      OUTPUT_PATH: /app/output
      ERROR_PATH: /app/error
      JAVA_OPTS: "-Xmx512m -Xms256m"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./error:/app/error
    depends_on:
      - minio
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  minio_data: