version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s
    networks:
      - transaction-network
    restart: unless-stopped

  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      mc mb minio/transactions;
      mc policy set public minio/transactions;
      exit 0;
      "
    networks:
      - transaction-network

  transaction-file-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-file-bridge
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: transactions
      INPUT_PATH: /app/input
      OUTPUT_PATH: /app/output
      ERROR_PATH: /app/error
      JAVA_OPTS: "-Xmx512m -Xms256m"
    volumes:
      - /c/Users/antar/Downloads/transaction-file-bridge/transaction-file-bridge/src/main/resources/input:/app/input
      - /c/Users/antar/Downloads/transaction-file-bridge/transaction-file-bridge/src/main/resources/output:/app/output
      - /c/Users/antar/Downloads/transaction-file-bridge/transaction-file-bridge/src/main/resources/error:/app/error
    depends_on:
      minio:
        condition: service_healthy
      minio-client:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - transaction-network
    restart: unless-stopped

volumes:
  minio_data:
    driver: local

networks:
  transaction-network:
    driver: bridge