spring:
  application:
    name: transaction-file-bridge
camel:
  health:
    consumers-enabled: false
  springboot:
    name: TransactionBridge
  component:
    minio:

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

# File directory paths
input:
  directory: ${INPUT_PATH:/app/input}
output:
  directory: ${OUTPUT_PATH:/app/output}
error:
  directory: ${ERROR_PATH:/app/error}

# MinIO configuration
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:transactions}

logging:
  level:
    org.apache.camel: INFO
    wael_project.transaction_file_bridge: DEBUG