spring:
  application:
    name: transaction-file-bridge
camel:
  springboot:
    name: TransactionBridge
  component:
    minio:


management:
  endpoints:
    web:
      exposure:
        include: health,metrics
input:
  directory: ./input

output:
  directory: ./output

error:
  directory: ./error
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: transactions

logging:
  level:
    org.apache.camel: INFO
    wael_project.transaction_file_bridge: DEBUG